### ISSUE TITLE
Support of Shutter Tilt in automation 

### ISSUE THREAD

**Issue by JosefRypacek** [emontnemery/hatasmota#217]
Tasmota got better support of shutters and tilting and it is possible to specify [position and tilt at once](https://tasmota.github.io/docs/Blinds-and-Shutters/#venetian-blind-support).

E.g. MQTT message `cmnd/tasmota_48CEEC/ShutterPosition1 0,-45` will close blinds and then tilt to 45°.

With these single combined command there is no need to wait between ShutterPosition and ShutterTilt command. 

I'm sure this would be very helpful to implement into automation as it's possible to set only position at the moment.

**Comment by stefanbode** [comment]
HA can do tilt and position now. Anyhow this is not simultaneously. But this is also not required because you can set the positon first and during movement set the target tilt. The tilt on shutters is a bit hidden in HA. Setting the tilt first will most likely not work.

**Comment by JosefRypacek** [comment]
That's true, but I have multiple automations (morning, evening, sun azimuth change) to control a bunch of blinds. It's already complicated now and I don't want to double each device in each automation. Maybe there is some HA feature to simplify it, but I'm not aware. 

I'm currently using MQTT publish instead of shutter device in automations to workaround this and set both properties in one step.

**Comment by stefanbode** [comment]
@JosefRypacek : This is a problem of HA. The services of the "cover" do not allow any call of tilt and position. This maybe an enhancement to HA. Anyhow I believe there is not much support because a quite rare use case. I use NodeRed for automation. Here you can define sub-workflows. This is a workaround to get your automation simplified. NodeRed anyhow is a very powerful way to make complex automations

**Comment by JosefRypacek** [comment]
OK, thanks, that makes sense. 

I just thought if there is possibility to add one more field to the device action, but now I see it's not so straightforward and would need to be handled in [HA](https://www.home-assistant.io/integrations/cover/).

<img width="1064" alt="Snímek obrazovky 2023-07-26 v 21 41 33" src="https://github.com/emontnemery/hatasmota/assets/5843126/c4c17ffd-08c3-4d33-8d5b-cec9425dd609">

**Comment by stefanbode** [comment]
This may be possible but it is not part of the integration. I would assume this is HA core enhancement to the cover item.
