### ISSUE TITLE
Remove release pinning

### ISSUE THREAD

**Issue by fabaff** [emontnemery/hatasmota#60]
At the moment the requirements are pinned. 

```text
attrs==19.3.0
voluptuous==0.12.1
```

This is an issue for distribution packages. E. g., the Fedora RPM of `attrs` package is already at 20.3.0. The `voluptuous` NixOS package is still at 0.12.0. This blocks the usage of the system-wide Python packages. It works for Home Assistant but it's still possible that there is a miss-match one say that will cause issues.

Could you please consider to soften the requirements? Thanks

**Comment by emontnemery** [comment]
Yes, sure. Any best practice for how to this in the best way?

**Comment by emontnemery** [comment]
Fixed in #61
