### ISSUE TITLE
Alexa losing iFan03 Light on home assistant reboot

### ISSUE THREAD

**Issue by RubberDinero** [emontnemery/hatasmota#66]
Every time I restart home assistant, only the fan portion continues to work. The light becomes unresponsive through the Alexa app. 
I have an iFan03 in my living room and dining room and both have the same issue. 
HomeKit has no problems staying in sync with all entities.
I may have posted this in the wrong area.
Not sure how to delete

**Comment by emontnemery** [comment]
I think this is a duplicate of https://github.com/home-assistant/core/issues/45017, could you try the fix in #45403?

**Comment by RubberDinero** [comment]
I’m such a noob with github. Meant to reply to this one and ended to replying to a different post. With Tasmota being in beta, I expect a few issues. I’ll close this issue.
