### ISSUE TITLE
Feature Request:  Device Firmware version as a sensor

### ISSUE THREAD

**Issue by M0E-lnx** [emontnemery/hatasmota#77]
I would like to see the Device Firmware version reported as a sensor please.  This would allow monitoring for outdated firmware versions by tracking sensors on homeassistant.

**Comment by emontnemery** [comment]
Do you mean you want this:
![image](https://user-images.githubusercontent.com/14281572/114994594-37e8f480-9e9d-11eb-82d3-6f6185efc1d5.png)

But also as a sensor?

**Comment by M0E-lnx** [comment]
Yes!.. that, but as a sensor entity or an attribute so it can  be picked up somewhere in homeassistant

**Comment by emontnemery** [comment]
This is fixed by #86 which will be included in Home Assistant 2021.5
